version: "3"

services:
    node:
        image: node:alpine
        user: node
        working_dir: /home/node/app
        entrypoint: node
        volumes:
            - .:/home/node/app

    npm:
        image: node:alpine
        user: node
        working_dir: /home/node/app
        entrypoint: npm
        volumes:
            - .:/home/node/app

    shell:
        image: alpine:latest
        user: 1000:1000
        working_dir: /app
        volumes:
            - .:/app
